platform :ios, '8.0'

use_frameworks!

target 'JXLiCai' do

pod 'IQKeyboardManagerSwift', '~> 4.0'
pod 'Kingfisher', '~> 3.10'#图片处理
pod 'Alamofire', '~> 4.5'#网络库'
pod 'SnapKit', '~> 3.2'#布局
pod 'ZKProgressHUD'#提示框


end
